version: '3'
services:
  server:
    image: prisma-test-server:latest
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./.graphqlconfig.yml:/project/.graphqlconfig.yml
      - ./datamodel.prisma:/project/datamodel.prisma
      - ./index.js:/project/index.js
      - ./prisma.yml:/project/prisma.yml
      - ./src:/project/src
    environment:
      # needs to be an http address or else prisma freaks out
      PRISMA_ENDPOINT: http://prisma:4466
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
      - "4466:4466"
    # networks:
    #   - frontend_client
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:

# networks:
#   frontend_client:
#     external: true
